# Generated by Django 6.1 on 2026-09-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stock_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. Shown as the POS product card background when uploaded.', null=True, upload_to='products/'),
        ),
    ]
