# Generated by Django 6.1 on 2026-09-11 07:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_payment_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Product tax percent stored at sale time.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
    ]
